**LABEL ENCODER**

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=pd.DataFrame({"Fruits":["Apple","Orange","Grapes","Apple","Grapes"]})
df['Fruits']=le.fit_transform(df['Fruits'])

In [2]:
data=pd.DataFrame({"Bikes":["Classic 350","Scrambler","Duke 250","Scrambler","Classic 350"],
                   "Brand":["RE","Triumph","KTM","Triumph","RE"]
                  })
data

         Bikes    Brand
0  Classic 350       RE
1    Scrambler  Triumph
2     Duke 250      KTM
3    Scrambler  Triumph
4  Classic 350       RE

In [3]:
data=pd.DataFrame({"Bikes":["Classic 350","Scrambler","Duke 250","Scrambler","Classic 350"]})
data['Bikes']=le.fit_transform(data['Bikes'])
data

   Bikes
0      0
1      2
2      1
3      2
4      0

**ONE HOT ENCODER**

In [4]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
df=pd.DataFrame({"IPL":["RCB","MI","LSG","PBKS","DC","RR","SRH","GT","CSK",]})
data=ohe.fit_transform(df[['IPL']])
names=ohe.get_feature_names_out(['IPL'])
df1=pd.DataFrame(data,columns=names)
df1

,IPL_CSK,IPL_DC,IPL_GT,IPL_LSG,IPL_MI,IPL_PBKS,IPL_RCB,IPL_RR,IPL_SRH
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df=pd.DataFrame({"Fruits":["Apple","Orange","Grapes","Apple","Grapes"]})
data=ohe.fit_transform(df[['Fruits']])
names=ohe.get_feature_names_out(['Fruits'])
df1=pd.DataFrame(data,columns=names)
df1

   Fruits_Apple  Fruits_Grapes  Fruits_Orange
0           1.0            0.0            0.0
1           0.0            0.0            1.0
2           0.0            1.0            0.0
3           1.0            0.0            0.0
4           0.0            1.0            0.0

In [6]:
data=pd.DataFrame({"Bikes":["Classic 350","Scrambler","Duke 250","Scrambler","Classic 350"]})
df=ohe.fit_transform(data[["Bikes"]])
names=ohe.get_feature_names_out(["Bikes"])
df1=pd.DataFrame(df,columns=names)
df1

   Bikes_Classic 350  Bikes_Duke 250  Bikes_Scrambler
0                1.0             0.0              0.0
1                0.0             0.0              1.0
2                0.0             1.0              0.0
3                0.0             0.0              1.0
4                1.0             0.0              0.0

**ASSIGNMENT TO WORK REALTIME DATASET**

In [7]:
data=pd.read_csv('/content/Products.csv')

In [8]:
data.head()

,product_id,product_name,category,concern,skin_type,key_ingredient,size,mrp,cost_price,stock_qty,launch_date
0,P001,2% Salicylic Acid Face Serum,Serum,Acne Control,Oily / Acne-Prone,Salicylic Acid,30ml,549,247,220,15-01-2022
1,P002,10% Niacinamide Face Serum,Serum,Oil Control,Oily / Combination,Niacinamide,30ml,599,265,240,10-09-2021
2,P003,Vitamin C 10% Face Serum,Serum,Brightening,All Skin Types,Vitamin C,30ml,699,315,180,01-05-2022
3,P004,Alpha Arbutin 2% Serum,Serum,Pigmentation,All Skin Types,Alpha Arbutin,30ml,649,292,160,18-03-2022
4,P005,Retinol 0.3% Face Serum,Serum,Anti-Ageing,Normal / Dry,Retinol,30ml,699,318,140,11-08-2022

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      28 non-null     object
 1   product_name    28 non-null     object
 2   category        28 non-null     object
 3   concern         28 non-null     object
 4   skin_type       28 non-null     object
 5   key_ingredient  28 non-null     object
 6   size            28 non-null     object
 7   mrp             28 non-null     int64
 8   cost_price      28 non-null     int64
 9   stock_qty       28 non-null     int64
 10  launch_date     28 non-null     object
dtypes: int64(3), object(8)
memory usage: 2.5+ KB

In [10]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

**LABEL ENCODER**

In [17]:
Le=LabelEncoder()
data['product_name']=Le.fit_transform(data['product_name'])
data

,product_id,product_name,category,concern,skin_type,key_ingredient,size,mrp,cost_price,stock_qty,launch_date
0,P001,1,Serum,Acne Control,Oily / Acne-Prone,Salicylic Acid,30ml,549,247,220,15-01-2022
1,P002,0,Serum,Oil Control,Oily / Combination,Niacinamide,30ml,599,265,240,10-09-2021
2,P003,27,Serum,Brightening,All Skin Types,Vitamin C,30ml,699,315,180,01-05-2022
3,P004,3,Serum,Pigmentation,All Skin Types,Alpha Arbutin,30ml,649,292,160,18-03-2022
4,P005,20,Serum,Anti-Ageing,Normal / Dry,Retinol,30ml,699,318,140,11-08-2022
5,P006,14,Serum,Hydration,Dry / Dehydrated,Hyaluronic Acid,30ml,599,258,210,05-12-2021
6,P007,2,Serum,Exfoliation,Oily / Combination,AHA + BHA,30ml,699,322,130,20-02-2023
7,P008,12,Serum,Anti-Ageing,Normal / Mature,Retinoid,30ml,799,358,120,12-05-2023
8,P009,10,Moisturizer,Barrier Repair,Dry / Sensitive,Ceramide,50g,349,145,300,01-10-2022
9,P010,26,Moisturizer,Hydration,All Skin Types,Vitamin B5,50g,399,162,280,22-04-2022
10,P011,25,Moisturizer,Soothing,Sensitive,Sepicalm,50g,349,148,250,18-11-2021
11,P012,16,Moisturizer,Nourishment,Dry,Marula Oil,50g,449,197,190,05-01-2023
12,P013,22,Sunscreen,Sun Protection,All Skin Types,SPF 50,50g,399,168,350,12-02-2022
13,P014,23,Sunscreen,Sun Protection,All Skin Types,SPF 60,50g,499,211,260,10-03-2023
14,P015,5,Sunscreen,Sun Protection,Oily / Combination,SPF Blend,50g,449,192,170,01-07-2023
15,P016,24,Cleanser,Acne Control,Oily / Acne-Prone,Salicylic Acid,100ml,299,117,320,16-08-2021
16,P017,18,Cleanser,Gentle Cleansing,Sensitive / Dry,Oat Extract,100ml,299,121,290,15-06-2022
17,P018,11,Cleanser,Exfoliation,Normal / Oily,Glycolic Acid,100ml,349,143,230,03-04-2023
18,P019,19,Toner,Exfoliation,Sensitive,PHA,150ml,399,166,180,30-09-2022
19,P020,21,Toner,Hydration,All Skin Types,Rose Water,150ml,349,139,210,17-06-2023
20,P021,9,Eye Care,Dark Circles,All Skin Types,Caffeine,30g,399,157,150,08-12-2022
21,P022,17,Eye Care,Anti-Ageing,Mature / Dry,Peptides,30g,499,218,110,05-08-2023
22,P023,4,Hair Care,Dandruff Control,Scalp Care,Piroctone Olamine,200ml,499,221,200,21-11-2022
23,P024,13,Hair Care,Hair Growth,Scalp Care,Redensyl,60ml,799,372,160,14-02-2023
24,P025,8,Hair Care,Damage Repair,Hair Care,Bond Repair Complex,200ml,599,266,135,09-09-2023
25,P026,6,Body Care,Body Brightening,All Skin Types,Niacinamide,200ml,449,182,220,03-10-2023
26,P027,7,Body Care,Body Acne,Oily / Acne-Prone,Salicylic Acid,200ml,399,159,240,01-11-2023
27,P028,15,Lip Care,Lip Protection,All Skin Types,SPF 30,10g,249,92,260,12-12-2023

**ONE HOT ENCODING**

In [15]:
data=pd.read_csv('/content/Products.csv')
df=ohe.fit_transform(data[["product_name"]])
names=ohe.get_feature_names_out(["product_name"])
df1=pd.DataFrame(df,columns=names)
df1

,product_name_10% Niacinamide Face Serum,product_name_2% Salicylic Acid Face Serum,product_name_AHA BHA 10% Exfoliating Serum,product_name_Alpha Arbutin 2% Serum,product_name_Anti-Dandruff Shampoo,product_name_Aqualogica Lightweight Sunscreen,product_name_Body Lotion with Niacinamide,product_name_Body Wash with Salicylic Acid,product_name_Bond Repair Shampoo,product_name_Caffeine Under Eye Cream,...,product_name_Oat Extract Gentle Cleanser,product_name_PHA 3% Alcohol-Free Toner,product_name_Retinol 0.3% Face Serum,product_name_Rose Water Hydrating Toner,product_name_SPF 50 Sunscreen,product_name_SPF 60 PA++++ Sunscreen,product_name_Salicylic Acid Face Cleanser,product_name_Sepicalm 3% Moisturizer,product_name_Vitamin B5 Moisturizer,product_name_Vitamin C 10% Face Serum
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0