**LABEL ENCODER**

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=pd.DataFrame({"Fruits":["Apple","Orange","Grapes","Apple","Grapes"]})
df['Fruits']=le.fit_transform(df['Fruits'])

In [3]:
data=pd.DataFrame({"Bikes":["Classic 350","Scrambler","Duke 250","Scrambler","Classic 350"],
                   "Brand":["RE","Triumph","KTM","Triumph","RE"]
                  })
data

         Bikes    Brand
0  Classic 350       RE
1    Scrambler  Triumph
2     Duke 250      KTM
3    Scrambler  Triumph
4  Classic 350       RE

In [4]:
data=pd.DataFrame({"Bikes":["Classic 350","Scrambler","Duke 250","Scrambler","Classic 350"]})
data['Bikes']=le.fit_transform(data['Bikes'])
data

   Bikes
0      0
1      2
2      1
3      2
4      0

**ONE HOT ENCODER**

In [5]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
df=pd.DataFrame({"IPL":["RCB","MI","LSG","PBKS","DC","RR","SRH","GT","CSK",]})
data=ohe.fit_transform(df[['IPL']])
names=ohe.get_feature_names_out(['IPL'])
df1=pd.DataFrame(data,columns=names)
df1

,IPL_CSK,IPL_DC,IPL_GT,IPL_LSG,IPL_MI,IPL_PBKS,IPL_RCB,IPL_RR,IPL_SRH
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df=pd.DataFrame({"Fruits":["Apple","Orange","Grapes","Apple","Grapes"]})
data=ohe.fit_transform(df[['Fruits']])
names=ohe.get_feature_names_out(['Fruits'])
df1=pd.DataFrame(data,columns=names)
df1

   Fruits_Apple  Fruits_Grapes  Fruits_Orange
0           1.0            0.0            0.0
1           0.0            0.0            1.0
2           0.0            1.0            0.0
3           1.0            0.0            0.0
4           0.0            1.0            0.0

In [7]:
data=pd.DataFrame({"Bikes":["Classic 350","Scrambler","Duke 250","Scrambler","Classic 350"]})
df=ohe.fit_transform(data[["Bikes"]])
names=ohe.get_feature_names_out(["Bikes"])
df1=pd.DataFrame(df,columns=names)
df1

   Bikes_Classic 350  Bikes_Duke 250  Bikes_Scrambler
0                1.0             0.0              0.0
1                0.0             0.0              1.0
2                0.0             1.0              0.0
3                0.0             0.0              1.0
4                1.0             0.0              0.0

**ASSIGNMENT TO WORK REALTIME DATASET**

In [8]:
data=pd.read_csv('/content/Products.csv')

In [9]:
data.head()

,product_id,product_name,category,concern,skin_type,key_ingredient,size,mrp,cost_price,stock_qty,launch_date
0,P001,2% Salicylic Acid Face Serum,Serum,Acne Control,Oily / Acne-Prone,Salicylic Acid,30ml,549,247,220,15-01-2022
1,P002,10% Niacinamide Face Serum,Serum,Oil Control,Oily / Combination,Niacinamide,30ml,599,265,240,10-09-2021
2,P003,Vitamin C 10% Face Serum,Serum,Brightening,All Skin Types,Vitamin C,30ml,699,315,180,01-05-2022
3,P004,Alpha Arbutin 2% Serum,Serum,Pigmentation,All Skin Types,Alpha Arbutin,30ml,649,292,160,18-03-2022
4,P005,Retinol 0.3% Face Serum,Serum,Anti-Ageing,Normal / Dry,Retinol,30ml,699,318,140,11-08-2022

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      28 non-null     object
 1   product_name    28 non-null     object
 2   category        28 non-null     object
 3   concern         28 non-null     object
 4   skin_type       28 non-null     object
 5   key_ingredient  28 non-null     object
 6   size            28 non-null     object
 7   mrp             28 non-null     int64
 8   cost_price      28 non-null     int64
 9   stock_qty       28 non-null     int64
 10  launch_date     28 non-null     object
dtypes: int64(3), object(8)
memory usage: 2.5+ KB

In [11]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

**LABEL ENCODER**

In [12]:
Le=LabelEncoder()
data['product_name']=Le.fit_transform(data['product_name'])
data

,product_id,product_name,category,concern,skin_type,key_ingredient,size,mrp,cost_price,stock_qty,launch_date
0,P001,1,Serum,Acne Control,Oily / Acne-Prone,Salicylic Acid,30ml,549,247,220,15-01-2022
1,P002,0,Serum,Oil Control,Oily / Combination,Niacinamide,30ml,599,265,240,10-09-2021
2,P003,27,Serum,Brightening,All Skin Types,Vitamin C,30ml,699,315,180,01-05-2022
3,P004,3,Serum,Pigmentation,All Skin Types,Alpha Arbutin,30ml,649,292,160,18-03-2022
4,P005,20,Serum,Anti-Ageing,Normal / Dry,Retinol,30ml,699,318,140,11-08-2022
5,P006,14,Serum,Hydration,Dry / Dehydrated,Hyaluronic Acid,30ml,599,258,210,05-12-2021
6,P007,2,Serum,Exfoliation,Oily / Combination,AHA + BHA,30ml,699,322,130,20-02-2023
7,P008,12,Serum,Anti-Ageing,Normal / Mature,Retinoid,30ml,799,358,120,12-05-2023
8,P009,10,Moisturizer,Barrier Repair,Dry / Sensitive,Ceramide,50g,349,145,300,01-10-2022
9,P010,26,Moisturizer,Hydration,All Skin Types,Vitamin B5,50g,399,162,280,22-04-2022
10,P011,25,Moisturizer,Soothing,Sensitive,Sepicalm,50g,349,148,250,18-11-2021
11,P012,16,Moisturizer,Nourishment,Dry,Marula Oil,50g,449,197,190,05-01-2023
12,P013,22,Sunscreen,Sun Protection,All Skin Types,SPF 50,50g,399,168,350,12-02-2022
13,P014,23,Sunscreen,Sun Protection,All Skin Types,SPF 60,50g,499,211,260,10-03-2023
14,P015,5,Sunscreen,Sun Protection,Oily / Combination,SPF Blend,50g,449,192,170,01-07-2023
15,P016,24,Cleanser,Acne Control,Oily / Acne-Prone,Salicylic Acid,100ml,299,117,320,16-08-2021
16,P017,18,Cleanser,Gentle Cleansing,Sensitive / Dry,Oat Extract,100ml,299,121,290,15-06-2022
17,P018,11,Cleanser,Exfoliation,Normal / Oily,Glycolic Acid,100ml,349,143,230,03-04-2023
18,P019,19,Toner,Exfoliation,Sensitive,PHA,150ml,399,166,180,30-09-2022
19,P020,21,Toner,Hydration,All Skin Types,Rose Water,150ml,349,139,210,17-06-2023
20,P021,9,Eye Care,Dark Circles,All Skin Types,Caffeine,30g,399,157,150,08-12-2022
21,P022,17,Eye Care,Anti-Ageing,Mature / Dry,Peptides,30g,499,218,110,05-08-2023
22,P023,4,Hair Care,Dandruff Control,Scalp Care,Piroctone Olamine,200ml,499,221,200,21-11-2022
23,P024,13,Hair Care,Hair Growth,Scalp Care,Redensyl,60ml,799,372,160,14-02-2023
24,P025,8,Hair Care,Damage Repair,Hair Care,Bond Repair Complex,200ml,599,266,135,09-09-2023
25,P026,6,Body Care,Body Brightening,All Skin Types,Niacinamide,200ml,449,182,220,03-10-2023
26,P027,7,Body Care,Body Acne,Oily / Acne-Prone,Salicylic Acid,200ml,399,159,240,01-11-2023
27,P028,15,Lip Care,Lip Protection,All Skin Types,SPF 30,10g,249,92,260,12-12-2023

**ONE HOT ENCODING**

In [13]:
data=pd.read_csv('/content/Products.csv')
df=ohe.fit_transform(data[["product_name"]])
names=ohe.get_feature_names_out(["product_name"])
df1=pd.DataFrame(df,columns=names)
df1

,product_name_10% Niacinamide Face Serum,product_name_2% Salicylic Acid Face Serum,product_name_AHA BHA 10% Exfoliating Serum,product_name_Alpha Arbutin 2% Serum,product_name_Anti-Dandruff Shampoo,product_name_Aqualogica Lightweight Sunscreen,product_name_Body Lotion with Niacinamide,product_name_Body Wash with Salicylic Acid,product_name_Bond Repair Shampoo,product_name_Caffeine Under Eye Cream,...,product_name_Oat Extract Gentle Cleanser,product_name_PHA 3% Alcohol-Free Toner,product_name_Retinol 0.3% Face Serum,product_name_Rose Water Hydrating Toner,product_name_SPF 50 Sunscreen,product_name_SPF 60 PA++++ Sunscreen,product_name_Salicylic Acid Face Cleanser,product_name_Sepicalm 3% Moisturizer,product_name_Vitamin B5 Moisturizer,product_name_Vitamin C 10% Face Serum
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**ORDINAL ENCODING**

In [14]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Dist','FC','SC','TC','Fail']])
df=pd.DataFrame({"Ranks":["Dist","FC","SC","Fail","Dist",'Fail','FC']})
df['Ranks']=oe.fit_transform(df[['Ranks']])
df

   Ranks
0    0.0
1    1.0
2    2.0
3    4.0
4    0.0
5    4.0
6    1.0

**FEATURE SCALING**

* **NORMALISATION / L2 NORM / EUCLIDEAN NORM**

In [15]:
import pandas as pd
from sklearn.preprocessing import Normalizer
nor=Normalizer()
df=pd.DataFrame({"Weight":[65,80,75],"Height":[170,130,150]})
data=nor.fit_transform(df)
df1=pd.DataFrame(data,columns=df.columns)
df1

     Weight    Height
0  0.357137  0.934052
1  0.524097  0.851658
2  0.447214  0.894427

In [16]:
import pandas as pd
from sklearn.preprocessing import Normalizer
nor=Normalizer()
df=pd.DataFrame({"Exp":[1,2,3,4,5],"Sal":[35000,45000,50000,60000,75000]})
data=nor.fit_transform(df[['Exp','Sal']])
df1=pd.DataFrame(data,columns=df.columns)
df1

        Exp  Sal
0  0.000029  1.0
1  0.000044  1.0
2  0.000060  1.0
3  0.000067  1.0
4  0.000067  1.0

* **Standard Scalar / Z2-Score**

In [17]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df=pd.DataFrame({"Weight":[65,80,75],"Height":[170,130,110]})
data=sc.fit_transform(df)
df1=pd.DataFrame(data,columns=df.columns)
df1

     Weight    Height
0 -1.336306  1.336306
1  1.069045 -0.267261
2  0.267261 -1.069045

In [18]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df=pd.DataFrame({"Weight":[72,55,50],"Height":[182,130,145]})
data=sc.fit_transform(df)
df1=pd.DataFrame(data,columns=df.columns)
df1

     Weight    Height
0  1.380585  1.357553
1 -0.424795 -1.021978
2 -0.955790 -0.335575

MANUAL CALCULATION

In [19]:
import numpy as np
h=[72,55,50]
mh=np.mean(h)

print('height avg: ',mh)
#sum(xi-u)2
for i in h:
  ms=(i-mh)**2
  print(i,ms)

height avg:  59.0
72 169.0
55 16.0
50 81.0

In [20]:
total=(169+16+81)
sd=np.sqrt(total/3)
print(sd)

9.41629792788369

In [21]:
h=[72,55,50]
for i in h:
  print((i-mh)/sd)

1.3805850345393378
-0.4247953952428732
-0.9557896392964647

In [22]:
w=[182,130,145]
wh=np.mean(w)
print('weight avg: ',wh)
#sum(xi-u)2
for i in w:
  ms=(i-wh)**2
  print(i,ms)

weight avg:  152.33333333333334
182 880.1111111111105
130 498.7777777777782
145 53.777777777777914

In [23]:
total=(880.11+498.77+53.77)
sd=np.sqrt(total/3)
print(sd)

21.85291742536909

In [24]:
w=[182,130,145]
for i in w:
  print((i-wh)/sd)

1.3575609191762457
-1.0219840627506576
-0.3355768564255894

**SUPERVISED LEARNING**
1. **LINEAR REGRESSION**

In [25]:
from sklearn import datasets
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_file',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_classification',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll',
 'textwrap']

**Diabetes Dataset**

In [26]:
import pandas as pd
from sklearn.datasets import load_diabetes

In [27]:
inout=load_diabetes()
inout

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [28]:
df=pd.DataFrame(inout.data,columns=inout.feature_names)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [30]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [31]:
df['Target']=inout.target
df.head(5)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [32]:
X=df.drop('Target',axis=1)# only 1 or 0
X.head()
#or
#X=df.iloc[:,:-1]
#X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [33]:
y=df['Target']
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: Target, dtype: float64

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [35]:
X_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
225,0.030811,0.050680,0.032595,0.049415,-0.040096,-0.043589,-0.069172,0.034309,0.063015,0.003064
412,0.074401,-0.044642,0.085408,0.063187,0.014942,0.013091,0.015505,-0.002592,0.006207,0.085907
118,-0.056370,0.050680,-0.010517,0.025315,0.023198,0.040022,-0.039719,0.034309,0.020609,0.056912
114,0.023546,-0.044642,0.110198,0.063187,0.013567,-0.032942,-0.024993,0.020655,0.099241,0.023775
364,0.001751,0.050680,-0.006206,-0.019442,-0.009825,0.004949,-0.039719,0.034309,0.014821,0.098333
...,...,...,...,...,...,...,...,...,...,...
106,-0.096328,-0.044642,-0.076264,-0.043542,-0.045599,-0.034821,0.008142,-0.039493,-0.059471,-0.083920
270,0.005383,0.050680,0.030440,0.083844,-0.037344,-0.047347,0.015505,-0.039493,0.008641,0.015491
348,0.030811,-0.044642,-0.020218,-0.005670,-0.004321,-0.029497,0.078093,-0.039493,-0.010903,-0.001078
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
102,-0.092695,-0.044642,0.028284,-0.015999,0.036958,0.024991,0.056003,-0.039493,-0.005142,-0.001078

In [36]:
y_train

225    208.0
412    261.0
118    179.0
114    258.0
364    262.0
       ...
106    134.0
270    202.0
348    148.0
435     64.0
102    302.0
Name: Target, Length: 309, dtype: float64

In [37]:
X_test.shape

(133, 10)

In [38]:
y_test.shape

(133,)

**LINEAR REGRESSION**

In [39]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred=model.predict(X_test)

In [41]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2=r2_score(y_test,y_pred)
r2

0.4772897164322617

In [42]:
print("Training Efficiency : ",model.score(X_train,y_train))
print("Testing Efficiency : ",model.score(X_test,y_test))

Training Efficiency :  0.5244124363545944
Testing Efficiency :  0.4772897164322617

In [43]:
mse=mean_squared_error(y_test,y_pred)
mse

2821.750981001311

In [44]:
mae=mean_absolute_error(y_test,y_pred)
mae

41.91937845679274

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [46]:
from sklearn.linear_model import LinearRegression
model=LinearRegression().fit(X_train,y_train)

In [47]:
y_pred=model.predict(X_test)

In [48]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2=r2_score(y_test,y_pred)
r2

0.4772897164322617

In [49]:
print("Training Efficiency : ",model.score(X_train,y_train))
print("Testing Efficiency : ",model.score(X_test,y_test))

Training Efficiency :  0.5244124363545944
Testing Efficiency :  0.4772897164322617

**2.1 RIDGE REGRESSION**

In [50]:
from sklearn.linear_model import Ridge
Rmodel=Ridge(alpha=0.01)
Rmodel.fit(X_train,y_train)

Ridge(alpha=0.01)

In [51]:
y_pred=Rmodel.predict(X_test)

In [52]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2=r2_score(y_test,y_pred)
r2

0.4776718084100272

In [53]:
print("Training Efficiency : ",Rmodel.score(X_train,y_train))
print("Testing Efficiency : ",Rmodel.score(X_test,y_test))

Training Efficiency :  0.5226476114183282
Testing Efficiency :  0.4776718084100272

**2.2 LASSO REGRESSION**

In [54]:
from sklearn.linear_model import Lasso
Lamodel=Lasso(alpha=0.009)
Lamodel.fit(X_train,y_train)

Lasso(alpha=0.009)

In [55]:
y_pred=Lamodel.predict(X_test)

In [56]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2=r2_score(y_test,y_pred)
r2

0.4786748631868004

In [57]:
print("Training Efficiency : ",Lamodel.score(X_train,y_train))
print("Testing Efficiency : ",Lamodel.score(X_test,y_test))

Training Efficiency :  0.5233202173758813
Testing Efficiency :  0.4786748631868004